version: 2
jobs:
  build:
    docker:
      - image: vvakame/review:4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Setup
          command: npm install
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Build PDF
          command: npm run pdf
      - run:
          name: Preparing artifacts
          command: |
            mkdir -p /tmp/artifacts
            cp ./articles/*.pdf /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: /
